version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - celery
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings
  celery:
     build: .
     command: celery -A myshop worker -l info -B
     depends_on:
      - redis
     environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings
  redis:
    image: redis:alpine
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web interface port
    depends_on:
      - web