# Generated by Django 4.2.16 on 2024-11-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
