# Generated by Django 4.2.16 on 2024-12-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_delete_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="country",
            field=models.CharField(
                choices=[
                    ("RU", "Russia"),
                    ("GE", "Germany"),
                    ("JP", "Japan"),
                    ("ND", "No Data"),
                ],
                default="ND",
                max_length=2,
                verbose_name="Страна производства",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="country",
            field=models.CharField(
                choices=[
                    ("RU", "Russia"),
                    ("GE", "Germany"),
                    ("JP", "Japan"),
                    ("ND", "No Data"),
                ],
                default="ND",
                max_length=2,
                verbose_name="Страна производства",
            ),
        ),
    ]
