# Generated by Django 4.2.16 on 2024-12-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_alter_product_options_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Бренд", "verbose_name_plural": "Бренды"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
    ]
