# Generated by Django 4.2.16 on 2024-12-27 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_brand_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
    ]
