# Generated by Django 4.2.16 on 2024-12-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_alter_comment_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
