# Generated by Django 4.2.16 on 2024-12-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0029_profilecomment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfileComment",
        ),
    ]
