# Generated by Django 4.2.16 on 2024-12-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0035_alter_visit_options_alter_visit_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["first_name"],
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="shop_profil_user_id_42814b_idx"),
        ),
    ]
