# Generated by Django 4.2.16 on 2024-12-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0036_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profile",
            name="shop_profil_user_id_42814b_idx",
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["first_name"], name="shop_profil_first_n_4b7096_idx"
            ),
        ),
    ]
